### ISSUE TITLE
Readme - Add Ensenya el Cor, Balanç Social context

### ISSUE THREAD

**Issue by sseerrggii** [Show-your-Heart/ShowYourHeart-docs#2]
On Readme add some context of the Ensenya el Cor/Balanç Social/Balance Social history , for search purposes. 

On my Cooperative we do "Balanç Social" and me or my colleges could search for this term on Github in order to find the Open Source repositori of Balanç Social

I suggest to add more historical context of Balanç Social on Readme

**Comment by sergioespana** [comment]
Hecho!
